### ISSUE TITLE
Exponentiation on GT elements by 0 is not one

### ISSUE THREAD

**Issue by Fasjul** [gdanezis/bplib#10]
Hello !
I noticed that exponentiating a GT element by 0 gave the same result as exponentiating by 1 (identity). As a consequence, the following code returns False:
>G = BpGroup()
>g = G.pair(G.gen1(), G.gen2())
>g** 0 == g.one(G)

So does this one :
>g** (-2) * g** (2) == g** 0

But these all return True:
>g** 0 == g
>g** 1 == g
>g** (-2) * g** (2) == g.one(G)

**Comment by gdanezis** [comment]
I have integrated your patch -- many thanks.
