### ISSUE TITLE
Qeustion : What are the possible values for the "nid" in BpGroup() ?

### ISSUE THREAD

**Issue by karuppiah7890** [gdanezis/bplib#3]
Looks like the Bilinear Mapping has two different groups G1 and G2 mapping to GT. But I want a mapping from G and G to GT. So, is it possible for me give a different value (curve ID) for nid and get one ? But I don't see curve IDs as integers. I see them as "fp254bnb". And you have provided it as an integer value for default value, which is 1. Does that mean we get something else for value 0 ? A non fp254bnb curve ? what does that mean ?

**Comment by gdanezis** [comment]
I am not entirely sure I understand the question. Currently there is only one choice (the default) for G1, G2, and GT and it is the case that G1 =/= G2. So to some extent there is little flexibility there.

**Comment by karuppiah7890** [comment]
@gdanezis Okay. Actually, this was a long time ago, and now I don't remember what I was doing. It was too much math for me to handle. I think I will just close it :)
