### ISSUE TITLE
Minor installation issue on macOS High Sierra.

### ISSUE THREAD

**Issue by asonnino** [gdanezis/bplib#4]
Installation through `pip install bplib` doesn't work on macOS; however cloning the repo and executing `python setup.py install` works fine.

Tested with python 2.7 and python 3 on macOS High Sierra. Here is the error:
```
build/temp.macosx-10.13-x86_64-3.6/bplib._bplib.c:483:10: fatal error: 'openssl/crypto.h' file not found
  #include <openssl/crypto.h>
           ^~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for bplib
  Running setup.py clean for bplib
```

**Comment by gdanezis** [comment]
Did you ever manage to fix this? If so could you submit a patch to fix it for others?

**Comment by asonnino** [comment]
The problem vanished when I updated my Mac. The problem was probably coming from openSSL (maybe an old or broken installation of openSSL) -- now everything is working fine.
